---
version: "3.8"
services:
  api:
    build: api/
    image: "${registry}/movie-app-api"
    container_name: movie_app_api
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    environment:
      - HOST=database
      - PORT=3306
      - DATABASE=${database_name}
      - DBUSER=${database_user}
      - PASSWORD=${database_password}
    networks:
      - backend
    volumes:
      - images:/app/img
  #  webapp:
  #    build: webapp/
  #    image: "${registry}/movie-app-webapp"
  #    container_name: movie_app_webapp
  #    depends_on:
  #      - api
  #    ports:
  #      - "80:80"
  database:
    image: mariadb
    restart: always
    container_name: movie_app_db
    environment:
      - MYSQL_ROOT_PASSWORD=${database_root_password}
      - MYSQL_DATABASE=${database_name}
      - MYSQL_USER=${database_user}
      - MYSQL_PASSWORD=${database_password}
    ports:
      - "3306"
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql

networks:
  backend: {}

volumes:
  data: {}
  images: {}
